FROM silent198214/nutanix-lcm:latest

LABEL vendor="IDN Design Studio" \
      version="1.0" \
      maintainer="Sam Chen<silent198214@gmail.com>" \
      description="Nutanix LCM Server"

VOLUME ["/usr/local/apache2/htdocs/release"]

EXPOSE 80
